import mongoose from "mongoose";
const gigSchema=mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"User"
    },
    title:{
        type:String,
        required:true,
      unique:true  
    },
    categoryone:{
        type:String,
        required:true
    },
    categorytwo:{
        type:String,
        required:true
    },
    servicetype:{
        type:String,
        required:true
    },
    metadata:{
        type:String,
        required:true
    },
    searchtag:[{
        type:String,
        required:true
    }],
    pkg:[{
        name:{
            type:String,
            required:true
        }
    }],
    pkgdescription:[{
        description:{
            type:String,
            required:true
        }
    }],
    deliverytime:[{
        days:{
            type:String,
            required:true
        }
    }],
    numofpages:[{
        pagesum:{
            type:String,
            required:true
        }
    }],
    numofproducts:[{
        productsnum:{
            type:String,
            required:true
        }
    }],
    customization:[{
        name:{
            type:Boolean,
        required:true
        }
    }],
    responsivedesing:[{
        name:{
            type:Boolean,
        required:true
        }
    }],
    contentupload:[{
        name:{
            type:Boolean,
        required:true
        }
    }],
    revisions:[{
        name:{
            type:String,
        required:true
        }
    }],
     price:[{
        name:{
            type:Number,
        required:true
        }
    }],
image:{
        type:String,
        required:true
},

});
const gig=mongoose.model("Gig",gigSchema);
export default gig;
